### ISSUE TITLE
sh -c of uname command prints out EBCDIC in ASCII build

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/perlport#26]
osname.pl:
```
eval "chop (\$osname = `sh -c 'uname -nmsr 2>&1'`)";
print $osname;
```

perl osname.pl should print out the ASCII uname with the newline on the end dropped. It doesn't. This comes from GNU make testing system.

This _does_ work:

```
eval "chop (\$osname = `uname -nmsr 2>&1`)";
print $osname;
```

**Comment by IgorTodorovskiIBM** [comment]
Seems to be an issue with the tag of the STDERR fd.  Doing this makes it passes:
`_TAG_REDIR_ERR= ./perl osname.pl`
Looks likes there's double conversion at some point.   Also, by removing 2>&1, it passes.

**Comment by MikeFultonDev** [comment]
you know more of perl than me now so transferring this over to you (hopefully fixed now?)

**Comment by MikeFultonDev** [comment]
fixed awhile ago
