### ISSUE TITLE
Improve install of Perl so that the locations are 'reasonable' when people download the binaries

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/perlport#43]
This is messy to get 'right'. Here is an interesting discussion: https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/38

I don't know if Perl itself creates any Perl files with #!/...perl directives in them. If so, then we should be installing into a 'well known' location - either /usr/local/bin or /usr/local/zot/bin (as opposed to /jenkins).
If however, Perl itself doesn't install any Perl files with #!/...perl directives, then perhaps the relocatable Perl install would be best and then it's the customer's problem if they install it in one location and then move it after it has generated some Perl code with #!/...perl directives (e.g. autoconf does this I think)
@IgorTodorovskiIBM thoughts?

**Comment by MikeFultonDev** [comment]
Option _i think_ is _relocatable-inc _

**Comment by IgorTodorovskiIBM** [comment]
`help2man` and likely other tools use `$Config{startperl}` which is hardcoded to the install prefix location.  We can probably set that to `#!/bin/env perl` so that it is determined based on the PATH environment variable.

**Comment by MikeFultonDev** [comment]
fixed awhile ago
