### ISSUE TITLE
CEE3728S when building perlport on z/OS 2.5

### ISSUE THREAD

**Issue by dougburns** [ZOSOpenTools/perlport#54]
The following error comes out when trying to build using z/OS 2.5:
```
CEE3728S The use of a function, which is not supported by this release of Language Environment was detected.
         From entry point Perl_pp_flock at compile unit offset +000000001D7E7DD0 at entry offset +0000000000000208 at address 000000001D7E7DD0.
```
This is similar to https://github.com/ZOSOpenTools/coreutilsport/issues/6, but involves new dummy functions that look like they've been added at z/OS 2.5.

Once I've got this working, I'll add my solution as a "common issue" in the Troubleshooting section of meta.

**Comment by MikeFultonDev** [comment]
@dougburns safe to close this now?

**Comment by dougburns** [comment]
@MikeFultonDev Yes, the modified version of your rmceertfm tool resolves this, so I'll close the issue.

However, I've found that the changes that I made to rmceertfm exposes an issue for using the tools at z/OS 2.4, so expect another pull request to address that.
